### ISSUE TITLE
Unexpected output using simple toy examples

### ISSUE THREAD

**Issue by phspo** [saezlab/CellNOptR#15]
Hello,

We are a group of cs students currently taking a course in reproducibility. We took great interest in your paper and are therefore trying to replicate your results. One of the first things we did was to create simple toy examples.  In one example we tried to connect two stimuli with a single readout and provide data in such way that a logical AND is forced. We attempted the same with a triple AND (three stimuli activating a readout node only when all three are activated).
The results did not match the model we expect, more specifically the calculated error does not seem to match the error we calculate manually (when inputting our "manually optimized" model).

We attached two notebooks and MIDAS files (.csv) as well as .sif files to illustrate our problem
[appendix.zip](https://github.com/saezlab/CellNOptR/files/3917415/appendix.zip)

Thanks in advance

**Comment by gabora** [comment]
Hi phspo, 
sorry for the delayed reaction. 
Many thanks for sending us a detailed report on the bug. 
I can confirm the strange behaviour of the AND gate.

I traced back the bug to the C-code, but it takes some time to debug it. 
Hope this will not risk the outcome of your assignment. 
best,
Attila

**Comment by gabora** [comment]
Hi phospo,

we found the bug and fixed it in the latest version. 
In short, simulating with a bitString with a _single_ TRUE value caused the issue. There is some model preprocessing before each simulation, where a matrix is subsetted by the bitString. Unfortunately, R converts matrices to vectors by default when only 1 column/row is selected. 

this bug is in the system since the beginning, but it is limited to the very rare cases when a model with a single edge would be the optimum.
