### ISSUE TITLE
Is there a limit of the number of nodes when using CNoptR

### ISSUE THREAD

**Issue by ucsdwxu** [saezlab/CellNOptR#6]
Hi,
I am just curious whether there is a limit of the nodes that can be analysed in CNoptR? If there is, what rough number is it?

Thank you
Weijun

**Comment by gabora** [comment]
Hello

I am not aware of any hard limits. We observed issues with models, where some nodes had many incoming edges (more than 10), but this issue was solved in a few months ago.  

Usually, we might face practical limits, because the optimisation requires more time as the number of edges increases. Unfortunately, there is no way to tell in advance how much time the optimisation will need to find a good minimum. 

I think CellNOpt is useful if you have targeted experiments, where you measure, let's say up to 100 proteins. If you deal with phosphorylation data from mass spect (few thousands of phosphosites), then maybe better to try PHONeMS.
I think @enio23 fitted models using the protein interaction network from Omnipath (www.omnipathdb.org), which contained more than 10-20k nodes. 

if you have a particular problem, we can discuss, which tool might fit the best. 

regards,
Attla

**Comment by ucsdwxu** [comment]
Hi Attla,

Thanks for replying and offering suggestions. I tried to search "PHONeMS" online but I could not seem to get a correct one which is for the model network purpose. Do you have a full name of it?

Thank you.

Best regards,
Weijun

**Comment by enio23** [comment]
Hello,

The main PHONEMeS publication can be found here: https://www.nature.com/articles/ncomms9033. There is also n ILP implementation which I would be happy to share. Note that PHONEMeS is a tool build to handle large-scale phosphoproteomics data and by combining them with interactions from Omnipath it tries to build logic models of signalling networks. What is the kind of data you are working with?

Cheers,
Enio

**Comment by gabora** [comment]
Sorry, my mistake, the correct name is PHONEMeS, as Enio corrected. 
You can find it in our github repo: 
https://github.com/saezlab/PHONEMeS

Description of the tool can be found on the github.io page:
https://saezlab.github.io/PHONEMeS/

**Comment by ucsdwxu** [comment]
Dear Enio and Attla,

Thank you for guiding. Actually I am very new to network and systems biology modelling but starting to learn these aspects from different sources and I find the work and tools developed from your lab are great. When coming to the dataset, I have not really decided clearly but if I have any thought, I would love to seek advice and discuss with you guys further. 

Best,
Weijun

**Comment by ucsdwxu** [comment]
Hi Enio,

I had a look at the PHONEMES page and may I ask whether it is compulsory for it to work on cluster? Also in the scripts for those current examples you have on the GitHub, to what extent I need to modify the content within the script for my own use? 

Thank you.
Cheers,
Weijun
