### ISSUE TITLE
CNORFeeder

### ISSUE THREAD

**Issue by ucsdwxu** [saezlab/CellNOptR#9]
Hi,

I am writing to ask a question for CNORFeeder. During the Weighting stage, the example in the tutorial uses "UniprotID=UniprotIDdream", may I know for my own case, how shall I define the UniprotID? Do I need to compile a file to contain the UniprotID information for all the protein nodes from my model sif file?

Thank you for help.

Best,
Weijun

**Comment by gabora** [comment]
Hello,

CNORFeeder uses a protein-protein interaction (PPI) network database to score each of the inferred edges. For this, the nodes in the user's network (from the SIF) must be mapped to the PPI network.
Since the SIF usually contains custom names for the nodes, Feeder needs a dictionary to know which node in the SIF corresponds to which node in the PPI network. 

I think, in the example, the PPI network is using UniprotIDs for the nodes, so if you want to use the same PPI network then you need to provide the uniprotIDs of all the nodes in your network. 

Alternatively, you can use Omnipath (omnipathdb.org) to generate a new PPI network based on gene names. Then you have to provide a dictionary between the SIF nodes and gene names. 

best,
Attila

**Comment by gabora** [comment]
In case you need more info about CNORFeeder, let's continue the discussion on the CNORFeeder's repo saezlab/CNORFeeder#1, this way others who are interested in CNORFeeder will find it easier.

**Comment by ucsdwxu** [comment]
Hi Attila,

I see now. So I need to compile an extra file which is a dictionary format for my nodes and their Uniprot IDs. Can I make this into a text file in my working directory or any other format you can suggest?

Many thanks.
Weijun
